# Site settings
title: Buidl
description: AI-powered dev bot that executes commands and builds things via Slack
baseurl: "/buidl"
url: "https://twilson63.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom settings
version: "1.1.0"
github_username: twilson63
repository: twilson63/buidl

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/